### ISSUE TITLE
スマホのデザイン調整

### ISSUE THREAD

**Issue by nakanishy** [dit-rohm/summer-hackathon#80]
・DHacksの文字を少し小さく
・jumbotronの上下paddingを狭く

**Comment by mikoim** [comment]
スケジュールの画像の解像度が低くてリンクを飛ばしたところで読みづらい．
もっと大きい画像に．

**Comment by nakanishy** [comment]
@mikoim 応急措置です。画像一枚ベタ貼り以外の方法を考えます
